# Generated by Django 3.2.9 on 2022-10-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
