# Generated by Django 3.2.9 on 2022-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stok", "0002_alter_status_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="code",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
