# Generated by Django 3.2.9 on 2022-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0002_stok_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
