# Generated by Django 3.2.9 on 2022-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_alter_stok_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stok',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
