# Generated by Django 3.2.9 on 2022-10-08 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_auto_20221008_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
