# Generated by Django 3.2.9 on 2022-10-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0006_alter_stok_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stok.category'),
        ),
    ]
