# Generated by Django 3.2.9 on 2022-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0007_stok_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stok',
            name='category',
        ),
        migrations.AddField(
            model_name='stok',
            name='categories',
            field=models.ManyToManyField(to='stok.Category'),
        ),
    ]
