# Generated by Django 3.2.9 on 2022-10-20 18:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0008_auto_20221012_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolumAdi', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cihaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_model', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='stoks')),
                ('description', ckeditor.fields.RichTextField()),
                ('SeriNo', models.CharField(max_length=200)),
                ('personel', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('gelis_tarihi', models.CharField(max_length=200)),
                ('cikis_tarihi', models.CharField(max_length=200)),
                ('bolum', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('categories', models.ManyToManyField(blank=True, to='stok.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Stok',
        ),
    ]
