# Generated by Django 3.2.9 on 2022-10-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0009_auto_20221020_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cihaz',
            old_name='gelis_tarihi',
            new_name='giris_tarihi',
        ),
    ]
