# Generated by Django 3.2.9 on 2022-10-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0010_rename_gelis_tarihi_cihaz_giris_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cihaz',
            name='bolums',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stok.bolum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='bolum',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
