# Generated by Django 3.2.9 on 2022-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0011_auto_20221029_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cihaz',
            name='bolum',
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='cikis_tarihi',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='giris_tarihi',
            field=models.DateField(max_length=200),
        ),
    ]
