# Generated by Django 3.2.9 on 2022-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0012_auto_20221029_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='cikis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='giris_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
