# Generated by Django 3.2.9 on 2022-10-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0013_auto_20221030_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='bolums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stok.bolum'),
        ),
    ]
