# Generated by Django 3.2.9 on 2022-10-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0014_alter_cihaz_bolums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
