# Generated by Django 3.2.9 on 2022-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0016_rename_bolums_cihaz_bolum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
