# Generated by Django 3.2.9 on 2022-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0017_alter_cihaz_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
