# Generated by Django 3.2.9 on 2022-11-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0018_alter_cihaz_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cihaz',
            name='categories',
        ),
        migrations.AddField(
            model_name='cihaz',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stok.category'),
        ),
    ]
