# Generated by Django 3.2.9 on 2022-11-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0019_auto_20221103_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cihaz',
            name='bolum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stok.bolum'),
        ),
        migrations.AlterField(
            model_name='cihaz',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stok.category'),
        ),
    ]
